### ISSUE TITLE
Update problem to 0.43.x and 0.44.x

### ISSUE THREAD

**Issue by 20Tauri** [20Tauri/DoxyDoxygen#48]
Some users currently experiment crash on update... Example:

``` python
AttributeError: DoxyBlock instance has no attribute 'translate'
```

or

``` python
KeyError: \'inner\'
```

To solve it, please restart sublime text.
If problem persist please leave a comment here

**Comment by 20Tauri** [comment]
No report after migration from 0.42.x to 0.44.5+ (docblockr branch)...
Seem fixed
